on:
  pull_request:
    branches:
    - master

name: Publish typed_json_dataclass
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: abatilo/actions-poetry
      env:
        INPUT_PYTHON_VERSION: 3.7
        INPUT_POETRY_VERSION: 1.0
      options: "--entrypoint entrypoint.sh"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Run tests
        run: |
          ls
          pwd
      - run: |
          poetry run python -m flake8 --show-source --import-order-style pep8 typed_json_dataclass
          tests
          poetry run python -m pytest --cov-report xml:codecov.xml --cov=typed_json_dataclass
          --cov-report=html --junit-xml=coverage.xml --cov-branch --cov-fail-under=100
          tests/
