on:
  pull_request:
    branches:
      - master

name: Publish typed_json_dataclass
jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-pypoetry-${{ hashFiles('**/pyproject.lock') }}
          restore-keys: |
            ${{ runner.os }}-pypoetry-
      - name: Install
        uses: abatilo/actions-poetry@v1.9.0
        with:
          python_version: 3.7.0
          poetry_version: 1.0
          args: install
      - name: Run flake8
        uses: abatilo/actions-poetry@v1.9.0
        with:
          python_version: 3.7.0
          poetry_version: 1.0
          args:
            run python -m flake8 --show-source --import-order-style pep8 typed_json_dataclass
            tests
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-pypoetry-${{ hashFiles('**/pyproject.lock') }}
          restore-keys: |
            ${{ runner.os }}-pypoetry-
      - name: Install
        uses: abatilo/actions-poetry@v1.9.0
        with:
          python_version: 3.7.0
          poetry_version: 1.0
          args: install
      - name: Run pytest
        uses: abatilo/actions-poetry@v1.9.0
        with:
          python_version: 3.7.0
          poetry_version: 1.0
          args:
            run python -m pytest --cov-report xml:codecov.xml --cov=typed_json_dataclass
            --cov-report=html --junit-xml=coverage.xml --cov-branch --cov-fail-under=100
            tests/
